### ISSUE TITLE
Excuse me, Show many space at the bottom of report`

### ISSUE THREAD

**Issue by thearabbit** [joseluisq/printd#10]
Excuse me, Show many space on report footer when print.
It have problem with `Printd or My Template`?

[jsFiddle](https://jsfiddle.net/theara/jfy3c967/)

Could help me?

**Comment by joseluisq** [comment]
It's a problem with your table component styles.

![image](https://user-images.githubusercontent.com/1700322/36342997-7c3324a0-1406-11e8-9033-7a046f039ad1.png)

Hiding "resize-triggers" div and space should be disappear.

**Comment by thearabbit** [comment]
Thanks, I will try to override this style.
Could you help me?
