### ISSUE TITLE
Compatibility with IE11

### ISSUE THREAD

**Issue by guyaumetremblay** [joseluisq/printd#13]
Hi,

Thanks for your excellent library. We are testing it in our Vue.js SPA and there is good chance that we'll implement it. 

Only think which is blocking is that it doesn't work with IE11. As explained in [this issue on stackoverflow](https://stackoverflow.com/questions/24673024/unable-to-print-iframe-content-from-parent-page-in-ie-11), when iframe src is dynamically set, IE11 contentWindow doesn't return the expected window object.

Quickfix is to replace `contentWindow.print` 
by
```
               var result = contentWindow.document.execCommand('print', false, null);
               if (!result)
                  contentWindow.print();
```

Tested on IE11, Edge, Firefox (windows), Safari (macOS, iOS), Chrome (windows / macOS / Android).

Regards, 

Guyaume Tremblay

**Comment by joseluisq** [comment]
Cool!
Thanks for your feedback.
For time reasons I cannot implement it by myself now.
Could you send a PR?

**Comment by joseluisq** [comment]
Done [v0.0.11](https://github.com/joseluisq/printd/releases/tag/v0.0.11)
