### ISSUE TITLE
Background colors do not show up

### ISSUE THREAD

**Issue by aka434112** [joseluisq/printd#16]
Background colors for elements such as div do not show up. Was able to reproduce this in the [playground](https://codepen.io/joseluisq/full/VzRpGb/) as well

**Comment by joseluisq** [comment]
It has nothing to do with `Printd` but with your styles.
Have a look at the updated example https://codepen.io/joseluisq/pen/VzRpGb (Chrome & Firefox tested)

**Note:** In Firefox you have to enable `Print backgrounds` when printing.

![image](https://user-images.githubusercontent.com/1700322/153188350-22b3427e-284e-4498-b79a-772def094451.png)
