### ISSUE TITLE
querySelectorAll error

### ISSUE THREAD

**Issue by azhdarshirinzada** [joseluisq/printd#19]
How can I select only needed elements among all, not only get one element by `getElementById`?

I didn't show the error because as I understood this behavior is normal for querySelectorAll.

Please give a feedback.

**Comment by joseluisq** [comment]
This library doesn't support multi-element printing right now. Instead, you might filter what elements you want before to print manually and wrap them around some container (temporary solution).

It could be "multi-element printing" a new feature on the future.
Feel free to send some PR or feature request.
