### ISSUE TITLE
cssText support `object style`?

### ISSUE THREAD

**Issue by thearabbit** [joseluisq/printd#2]
I base on `Vue`.
```js
.....
data(){
   return {
       cssObj:{
             myColor:{
                 color: 'red'
            }
       }
   }
}
```
Or have any solution?

**Comment by joseluisq** [comment]
Since this library supports only cssText, so you can find some alternatives to convert an object to string css. Maybe this https://github.com/natew/object-to-css could help you.

**Comment by thearabbit** [comment]
Thanks, I will try soon.
But don't how to install/using???

**Comment by joseluisq** [comment]
Other one options https://github.com/joakimbeng/to-css

**Comment by joseluisq** [comment]
> Thanks, I will try soon.
> But don't how to install/using???

In the same way that you installed printd.

**Comment by thearabbit** [comment]
Thanks again 👍

**Comment by thearabbit** [comment]
Excuse me, I can not import
```js
import toCss  from 'to-css';
````

**Comment by thearabbit** [comment]
Now it works fine

**Comment by joseluisq** [comment]
👍
