### ISSUE TITLE
Error on several pages

### ISSUE THREAD

**Issue by realtica** [joseluisq/printd#2]
## Expected Behavior

Print 2 or more pages well.

## Actual Behavior

When you try to print several pages there are the next errors:
![image](https://user-images.githubusercontent.com/852446/63062219-bbc72e00-bebd-11e9-99c3-b8bc08ce673f.png)

**Comment by joseluisq** [comment]
Printd has nothing to do with with the design of your components (html, css and js).
In the case of pages, Printd only puts your page into an iframe and then just launch the print dialog of your browser.

Additionally, I recommend to you just fix your design layout for your components. For example taking at look if your css styles are really supported in printing mode.
