### ISSUE TITLE
Add ability to print URLs

### ISSUE THREAD

**Issue by saulshanabrook** [joseluisq/printd#20]
Would it be possible to add the ability to print a page based on it's URL instead of it's dom nodes? I think you can set the `src` of the iframe to the URL and then you can print it once it loads: https://stackoverflow.com/questions/8240472/printing-a-web-page-using-just-url-and-without-opening-new-window

**Comment by saulshanabrook** [comment]
I have tried this functionality [here](https://github.com/jupyterlab/jupyterlab/blob/c2d82c2bf8771c119540c365cac18bec87df757d/packages/apputils/src/printing.ts#L82-L112) and can create a PR to add it.

**Comment by joseluisq** [comment]
> Would it be possible to add the ability to print a page based on it's URL instead of it's dom nodes? I think you can set the `src` of the iframe to the URL and then you can print it once it loads: [stackoverflow.com/questions/8240472/printing-a-web-page-using-just-url-and-without-opening-new-window](https://stackoverflow.com/questions/8240472/printing-a-web-page-using-just-url-and-without-opening-new-window)

The project was born with the idea of printing HTML elements. Sure, URL printing could be useful as a new feature.

Feel free to send some PR feature with a running example.
