### ISSUE TITLE
Firefox and Chrome on IPAD

### ISSUE THREAD

**Issue by MustafaHussaini** [joseluisq/printd#22]
## Expected Behavior

... Print Contents on ipad devices too.

## Actual Behavior

... Works with safari Browser but doesn't work with chrome or firexfox installed on IOS

## Steps to Reproduce the Problem

  1. ... 
  1. ...
  1. ...

## Specifications

  - Version: `v0.0.0`
  - Platform: `v0.0.0`
  - Node version: `v0.0.0`
  - Browser version: `v0.0.0`

**Comment by joseluisq** [comment]
I will close for inactivity. Feel free to re-open this issue if it's needed.
