### ISSUE TITLE
Image intermittently displayed on print preview

### ISSUE THREAD

**Issue by paulofelipe84** [joseluisq/printd#24]
I've got a vue.js dialog which I'm trying to print with printd. It has two images at the top.
The image on the right is always displayed on print preview, however, the one on the left (the first one in the code, in other words) is not displayed.

When I close the print preview and call printd several times, eventually the first image will actually be displayed, so I don't think it's a problem with the image itself. Its size is 10KB.

## Expected Behavior
All images are displayed on print preview.

## Actual Behavior
The first one of two images is displayed on print preview only after several tentatives (closing it and calling printd again), while the second image is properly displayed all the time.

## Steps to Reproduce the Problem
  1. Have a vue.js <v-dialog> with two images within two <v-flex> tags
  2. Call printd to print the dialog

## Specifications

  - Version: `v1.1.0`
  - Platform: `Ubuntu 16.04.4 LTS`
  - Node version: `v8.11.3`
  - Browser version: Chrome `v71.0.3578.98`

**Comment by joseluisq** [comment]
I guess that you are working with external images. Check out the issue #17.
I plan to add some support soon for external assets loading.

**Comment by paulofelipe84** [comment]
The problem is that I have another image from the same location, and that one is being normally loaded every time. Only the one that shows first is not being loaded, and still, that one gets loaded once in a while, so it's an intermittent behavior.

**Comment by joseluisq** [comment]
> The problem is that I have another image from the same location, and that one is being normally loaded every time. Only the one that shows first is not being loaded, and still, that one gets loaded once in a while, so it's an intermittent behavior.

Yeah, because the library is making a clone of your elements. that means we need to await for them.

**Comment by paulofelipe84** [comment]
So, even with a timeout of 2 seconds, it's still not happening. Should I add even more time?

**Comment by joseluisq** [comment]
[v1.2.0](https://github.com/joseluisq/printd/releases/tag/v1.2.0)

**Comment by paulofelipe84** [comment]
Sensational! Thank you so much Jose!
