### ISSUE TITLE
Have any hook before/after print dialog open/close?

### ISSUE THREAD

**Issue by thearabbit** [joseluisq/printd#3]
I would like to use`Hook`.
Eg: after print dialog closed

**Comment by joseluisq** [comment]
Sure, it's added to my ToDo list.

**Comment by thearabbit** [comment]
👍  Waiting you...

**Comment by joseluisq** [comment]
Events support is done in [v0.0.9](https://github.com/joseluisq/printd/releases/tag/v0.0.9).
Check out the [README](https://github.com/joseluisq/printd/#events) for more details.

**Comment by thearabbit** [comment]
Good job, I will try soon

**Comment by thearabbit** [comment]
Excuse me, this hook use when `before/after printing` or `before/after printing dialog`?

**Comment by joseluisq** [comment]
> Excuse me, this hook use when before/after printing or before/after printing dialog?

Sorry but my late response. 
Both events are `WindowEventHandlers` (printing dialog events):
Please check the README file at https://github.com/joseluisq/printd/#events

**Comment by thearabbit** [comment]
Thanks for your reply, I close
