### ISSUE TITLE
cssText not working

### ISSUE THREAD

**Issue by musicteachj** [joseluisq/printd#31]
The cssText is not applying to the print menu. Print dialog appears, but the cssText styles are not applied. Here is my code.

```js
<script>
import Printd from 'printd';

const d = new Printd();
const cssText = `
h1 {
  margin-left: 20px !important;
  color: blue;
  border: 1px solid purple;
  font-size: 8px;
}
t. {
  margin-left: 40%;
}
.barHome {
  margin-left: 40px;
}
`;

+

 methods: {
    printExample() {
      d.print( document.getElementById("exampleBarcodeContainer"), cssText );
    },
  }
```

This is my Vue-Things repo.
This is confusing, because this is the same syntax I have for 2 other projects using your library and they work as expected.

**Comment by joseluisq** [comment]
Wrap your styles using an array something like:

```ts
const d = new Printd()
d.print( document.getElementById("exampleBarcodeContainer"), [ cssText ] )
```

Please take a look into latest release  [v1.3.0](https://github.com/joseluisq/printd/releases/tag/v1.3.0)

**Comment by musicteachj** [comment]
Perfect! Thank you so much.
