### ISSUE TITLE
Feature: baseURI

### ISSUE THREAD

**Issue by jumika** [joseluisq/printd#33]
## Expected Behavior
We need a way to control the baseURI of the iframe.

## Actual Behavior
There is no way to control the baseURI of the iframe.

I'm trying to print an element that have relative url images inside. These are broken in the iframe because i can't set the base url.

I would prefer an option to set the base url, or an event that let you customize the html document loaded in the iframe.

**Comment by joseluisq** [comment]
In general, it's good idea.
It's no possible now to append elements using the underlying iframe to `document.head` due  [src/index.ts#L93](https://github.com/joseluisq/printd/blob/master/src/index.ts#L93).
But I'm preparing a PR to add the ability to passing `head` and `body` elements as options in the constructor.

Stay tuned.

**Comment by jumika** [comment]
Thank you.
For now i use my fork with another callback param to print method. This lets me modify the document before anything else happens to it. [https://github.com/jumika/printd](url)

**Comment by joseluisq** [comment]
I will plan to release a new version containing this improvements today evening.
New release is tracked on #35.

**Comment by joseluisq** [comment]
[v1.4.0](https://github.com/joseluisq/printd/releases/tag/v1.4.0) released. More info at https://github.com/joseluisq/printd#api
