### ISSUE TITLE
Improvement: Separate style strings and style urls parameters / allow relative urls in styles

### ISSUE THREAD

**Issue by jumika** [joseluisq/printd#34]
## Expected Behavior

Let us pass relative urls for the styles parameter.

## Actual Behavior

The styles array items are categorized to style string and style url by its content. The [isValidUrl ](https://github.com/joseluisq/printd/blob/master/src/index.ts#L3)function only allows absolute or root relative urls, so a simple relative url is categorized as a style string. This results html like this in the document: <style>my/relative-url.css</style>

## Steps to Reproduce the Problem

Pass a relative url in the styles parameter to print method.

A possible sollution is to separate styles and say styleUrls parameter.
Another one is to make styles param an object with two arrays, one for the inline styles one for the external css files.
Either way we can get rid of the isValidUrl function.

I think this whole issue stands for scripts also.

### Workaround

Pass document.baseURI in front of every relative url in styles:

`printer.print(el, [document.baseURI + "my/relative-url.css"])`

**Comment by joseluisq** [comment]
I think that the solution for this it's just prepend a `./` before which is considerate by ` isValidUrl` function.

```ts
isValidURL('my/relative-url.css')
// false
isValidURL('./my/relative-url.css')
// true
```

**Comment by jumika** [comment]
You are right. Thank you.
