### ISSUE TITLE
Cannot create Printd instance passing options object.

### ISSUE THREAD

**Issue by cManfredi** [joseluisq/printd#4]
## Expected Behavior

Creating an instance of Printd passing an options object should function without errors.

## Actual Behavior

Appending the iframe on the parent element results in an error "TypeError: parent.appendChild is not a function";
Passing manually window.document.body as the parent field of the options object doesn't solve the problem.

## Steps to Reproduce the Problem

const options = { headElements }
const p = new Printd(options)

## Specifications

  - Version: `v1.3.0`

**Comment by joseluisq** [comment]
Try to use the latest v1.4.0+ - https://github.com/joseluisq/printd/releases
