### ISSUE TITLE
doesnt Work  in Internet Explorer  when used in Angular 4

### ISSUE THREAD

**Issue by Audhut** [joseluisq/printd#6]
```ts
@Injectable()
export class PrintingService {
  constructor() { }

  PrintData(): void {
    console.log('PrintData start.');

    const cssText = `
    table {
      font-size: 85%;
      font-family: sans-serif;
      border-spacing: 0;
      border-collapse: collapse;
    }`;

    const d = new Printd();

    d.print( document.getElementById('mytable'), cssText );
   // window.location.reload();
   console.log('PrintData end.');
  }
}
```

using the above code to print. it works like charm in Chrome. but doesn't work in Internet Explorer for me.
A strange observation in Internet Explorer is that if i click print and then  refresh it opens the print dailog

**Comment by joseluisq** [comment]
What version of internet explorer do you use?

**Comment by Audhut** [comment]
Internet Explorer 11

**Comment by joseluisq** [comment]
I will verify it.

**Comment by Audhut** [comment]
attached is the src of the project for your reference.

[src.zip](https://github.com/joseluisq/printd/files/1719998/src.zip)

**Comment by joseluisq** [comment]
Cool 👍

**Comment by joseluisq** [comment]
**Printd** `v0.0.9` works fine on IE11

[View the demo running on IE11](https://user-images.githubusercontent.com/1700322/36154403-a03052de-10d1-11e8-994a-8a65a54a707e.gif)

What version of Printd do you use?

Here the demo source:
[printd_typescript_demo.zip](https://github.com/joseluisq/printd/files/1720233/printd_typescript_demo.zip)

_Note: Install [Parcel bundler](https://github.com/parcel-bundler/parcel) globally._

**Comment by Audhut** [comment]
"printd": "0.0.9",

**Comment by joseluisq** [comment]
Could you verify my example?

**Comment by joseluisq** [comment]
I updated your base service code. I recommend to you follow code below:

```ts
import { Injectable } from '@angular/core'
import { Printd } from 'printd'

@Injectable()
export class PrintingService {
  private d: Printd

  constructor () {
    console.log('PrintData start.')

    this.d = new Printd()
  }

  PrintData (): void {
    const cssText = `
    table {
      font-size: 85%;
      font-family: sans-serif;
      border-spacing: 0;
      border-collapse: collapse;
    }`

    this.d.print(document.getElementById('mytable'), cssText)

    console.log('PrintData end.')
  }
}

```

How I can't see any bug on Printd itself I will close this issue. 
Feel free to re-open it if you find any future issues.
