### ISSUE TITLE
importing styles via cdn not working

### ISSUE THREAD

**Issue by Chauding** [joseluisq/printd#71]
## Expected Behavior

I followed the example where I can use an array with the cdn link and then add `css classes` in the styles const. But it doesn't seem to get the css from the cnd link at all.

**Comment by joseluisq** [comment]
Please provide more details about it and one example in order to reproduce current issue(s).

**Comment by joseluisq** [comment]
I will close this issue due to inactivity. Feel free to open it again if it's needed.
