### ISSUE TITLE
How to change `default printer name` when printing?

### ISSUE THREAD

**Issue by thearabbit** [joseluisq/printd#88]
## Expected Behavior

Could be auto change `default printer name` by silence mode.

![image](https://user-images.githubusercontent.com/4495160/62101334-405f5d00-b2bf-11e9-976e-72a7c971d285.png)
 

## Steps to Reproduce the Problem

1. Have 3 `Printer` setup on my PC: Printer A, Printer B, Printer C
2. Create 3 Button to print: `Print A Button`, Print B Button`, `Print C Button`

I would like to print with `silence mod` by don't show `Printing Dialog`.
But it could change config `default printer name` like abov

## Workaround

...

## Specifications

  - Version: `v1.4`
  - Platform: `v0.0.0`
  - Node version: `v10.15`
  - Browser version: Chrome, Fierfox

**Comment by joseluisq** [comment]
> I would like to print with `silence mod` by don't show `Printing Dialog`.
> But it could change config `default printer name` like abov

In the end, Printd calls to `window.print()` which opens your **printing dialog** only. 
So Printd has nothing to do with [your browser preferences](https://blog.kiosksimple.com/2015/04/30/how-to-print-in-javascript-without-displaying-the-print-dialog-box/). Please take a look into the `README.md` file.

**Comment by thearabbit** [comment]
thanks for your reply.
Sorry I seem don't understand.
Could you share me, how to solve or any link? (change `printer name` before printing)
